import React from 'react';
import { motion } from 'framer-motion';
import { Bot, AlertTriangle, TrendingUp } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

const AnalysisResult = ({ analysis, isLoading, error }) => {
    if (isLoading) {
        return (
            <div className="w-full max-w-2xl mx-auto p-8 text-center">
                <div className="animate-spin w-12 h-12 border-4 border-accent border-t-transparent rounded-full mx-auto mb-4"></div>
                <p className="text-muted-foreground animate-pulse">Consulting the oracle...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="w-full max-w-2xl mx-auto p-6 bg-destructive/10 border border-destructive/20 rounded-xl text-center">
                <AlertTriangle className="w-10 h-10 text-destructive mx-auto mb-3" />
                <h3 className="text-lg font-bold text-destructive mb-2">Analysis Failed</h3>
                <p className="text-destructive-foreground/80">{error}</p>
            </div>
        );
    }

    if (!analysis) return null;

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="w-full max-w-3xl mx-auto bg-card border border-border rounded-xl shadow-2xl overflow-hidden"
        >
            <div className="bg-accent/10 p-4 border-b border-border flex items-center gap-2">
                <Bot className="w-5 h-5 text-accent" />
                <h2 className="font-bold text-lg text-foreground">AI Market Analysis</h2>
            </div>

            <div className="p-6 prose prose-invert max-w-none prose-headings:text-accent prose-a:text-blue-400">
                <ReactMarkdown>{analysis}</ReactMarkdown>
            </div>

            <div className="bg-background/50 p-4 border-t border-border text-center text-xs text-muted-foreground">
                Generated by Google Gemini • Not financial advice
            </div>
        </motion.div>
    );
};

export default AnalysisResult;
